# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65cc505be7d593b1af3bfe2d9245b31a40b8119f379621eb7152778c3ca9767a1f96aebc754d29d15e70176365a933d2454608ca2497ada20cd3c750c4d7078c

test:
  secret_key_base: 4bce88c8134023e1d54d5ef0de20f98cd06da403975678ef268f5901ab95d6ec41e43deb59c37173f3d741721817bdcd325bc9e3181b0b78c8a418473eb7dc78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
